### ISSUE TITLE
adminaddr file is always set

### ISSUE THREAD

**Issue by schwabe** [akumria/puppet-nullmailer#2]
We rewrite thte addresses for the hosts at our central mail server. Setting adminaddr always redirects these mails to the admin address.

I made the following fix for my local copy:

```
--- a/manifests/config.pp
+++ b/manifests/config.pp
@@ -16,10 +16,17 @@ class nullmailer::config {
     notify  => Class['nullmailer::service'],
   }

-  file { '/etc/nullmailer/adminaddr':
-    content => "$nullmailer::adminaddr\n",
-    require => Class['nullmailer::package'],
-    notify  => Class['nullmailer::service'],
+  if($nullmailer::adminaddr == "remove") {
+    file { '/etc/nullmailer/adminaddr':
+      ensure => absent,
+    }
+  }
+  else
+  {
+    file { '/etc/nullmailer/adminaddr':
+      content => "$nullmailer::adminaddr\n",
+      require => Class['nullmailer::package'],
+      notify  => Class['nullmailer::service'],
+    }
   }
-
 }
```

**Comment by akumria** [comment]
Hi,

Thanks for highlighting this use-case.

Your change is very nice, except I dislike the use of the magic string "remove" to cause the file to be removed.

What about, instead, if it checked that the variable was defined?

e.g.

```
if (defined($nullmailer::adminaddr)) {
   [ put in the file contents ]
} else {
    file { '/etc/nullmailer/adminaddr':
        ensure => absent,
    }  
}
```

Does that work for you? I think it would a bit cleaner.

**Comment by schwabe** [comment]
That would work for me too.

**Comment by schwabe** [comment]
But it might break the config for others which rely on the default being admin@domain instead of not being set.

**Comment by akumria** [comment]
Oh, I would envisage the default still being admin@domain, and for people who need it -- like you -- you can specify:

```
class {'nullmailer':
    adminaddr = undef,
}
```

Whereas most people would leave adminaddr as default or set it as:

```
class {'nullmailer':
    adminaddr => 'puppet-rockstar@example.com',
}
```

Will you have a chance to modify your pull request to use undef?

**Comment by akumria** [comment]
Thanks, I've taken your patch and corrected a few style nits.

Please try the updated version and let me know of any issues.

Many thanks.

**Comment by schwabe** [comment]
Yes works fine for me
